# Generated by Django 2.2.7 on 2019-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='tipo_asegurado',
        ),
        migrations.AddField(
            model_name='asociacionpolizas',
            name='tipo_asegurado',
            field=models.CharField(default='', max_length=10),
        ),
    ]
