# Generated by Django 2.2.7 on 2019-11-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='proveedor',
            new_name='proveedor_id',
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
