# Generated by Django 2.2.6 on 2019-10-11 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20190723_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Account', models.CharField(default='', max_length=50)),
                ('fecha_nacimiento', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=150)),
                ('mail', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(default='', max_length=50)),
                ('date_event', models.DateField()),
                ('cost', models.CharField(default='', max_length=150)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(default='', max_length=50)),
                ('detalle_tratamiento', models.CharField(default='', max_length=150)),
                ('tipodoc', models.CharField(default='', max_length=150)),
                ('datedoc', models.DateField()),
                ('montodoc', models.CharField(default='', max_length=30)),
                ('pago', models.CharField(default='', max_length=30)),
                ('user_reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolName', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=150)),
                ('permisos', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='evento',
            name='rolnameID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Rol'),
        ),
        migrations.AddField(
            model_name='account',
            name='rol_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Rol'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
