# Generated by Django 2.2.6 on 2019-10-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191011_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='montodoc',
            new_name='detalle_diagnostico',
        ),
        migrations.RenameField(
            model_name='reclamo',
            old_name='nombre_proveedor',
            new_name='nameReclamo',
        ),
        migrations.RenameField(
            model_name='reclamo',
            old_name='pago',
            new_name='numpoliza',
        ),
        migrations.RemoveField(
            model_name='reclamo',
            name='datedoc',
        ),
        migrations.RemoveField(
            model_name='reclamo',
            name='detalle_tratamiento',
        ),
        migrations.RemoveField(
            model_name='reclamo',
            name='tipodoc',
        ),
        migrations.RemoveField(
            model_name='reclamo',
            name='user_reclamo',
        ),
        migrations.AddField(
            model_name='reclamo',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Account'),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='rut',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(default='', max_length=50)),
                ('detalle_tratamiento', models.CharField(default='', max_length=150)),
                ('tipodoc', models.CharField(default='', max_length=30)),
                ('numdoc', models.CharField(default='', max_length=30)),
                ('datedoc', models.DateField()),
                ('montodoc', models.CharField(default='', max_length=30)),
                ('pago', models.CharField(default='', max_length=30)),
                ('reclamo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Reclamo')),
            ],
        ),
    ]
