# Generated by Django 2.2.6 on 2019-11-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191104_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
