# Generated by Django 2.2.6 on 2019-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191104_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='image',
            field=models.FileField(default=26, upload_to='post_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='detalle_diagnostico',
            field=models.CharField(default='', max_length=200),
        ),
    ]
