# Generated by Django 2.2.6 on 2019-11-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191106_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='image',
        ),
        migrations.AddField(
            model_name='documento',
            name='File',
            field=models.FileField(default=1, upload_to='post_Files'),
            preserve_default=False,
        ),
    ]
