# Generated by Django 2.2.6 on 2019-11-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191108_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='File',
            new_name='docfile',
        ),
    ]
