# Generated by Django 2.2.6 on 2019-11-13 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191108_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadoreclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_estado', models.CharField(default='Pendiente', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='reclamo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='estado_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Estadoreclamo'),
        ),
    ]
