# Generated by Django 2.2.6 on 2019-11-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191113_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoreclamo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
