# Generated by Django 2.2.6 on 2019-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191113_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='estado_id',
        ),
        migrations.AddField(
            model_name='reclamo',
            name='name_estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.DeleteModel(
            name='Estadoreclamo',
        ),
    ]
