# Generated by Django 2.2.6 on 2019-11-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191115_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='docfile',
            field=models.FileField(null=True, upload_to='post_Files'),
        ),
    ]
