# Generated by Django 2.2.6 on 2019-11-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_reclamo_num_clain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polizas',
            name='nombre_plan',
        ),
    ]
