# Generated by Django 2.2.6 on 2019-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191120_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='numPoliza',
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='num_claim',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
