# Generated by Django 2.2.7 on 2019-11-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191120_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='telefonoOficinaCliente',
            field=models.CharField(default='', max_length=15),
        ),
    ]
