# Generated by Django 2.2.6 on 2019-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191122_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociacionpolizas',
            name='tipo_asegurado',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='numPolizaLegacy',
        ),
        migrations.AddField(
            model_name='agentesventas',
            name='cod_agente',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='personas',
            name='telefonoOficina',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_asegurado',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='polizas',
            name='numPolizaLegacy',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='documento',
            name='docfile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='post_Files'),
        ),
    ]
