# Generated by Django 2.2.7 on 2019-11-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_personas_telefonooficinacliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='post_Files'),
        ),
    ]
